const servicesData = [
  {
    title: "Тонировка авто",
    description: "Аккуратная тонировка стекол для приватности, комфорта и более собранного образа автомобиля.",
    tag: "Film",
    image: "../assets/images/services/tonirovka.jpg",
    alt: "Тонировка авто",
  },
  {
    title: "Автозвук",
    description: "Подбор и установка акустики, усилителей и сабвуферов с чистой настройкой под салон.",
    tag: "Audio",
    image: "../assets/images/services/avtozvuk.jpg",
    alt: "Автозвук",
  },
  {
    title: "Установка bi-led линз",
    description: "Мощный и ровный свет с корректной светотеневой границей и современной оптикой.",
    tag: "Light",
    image: "../assets/images/services/bi-led-linzy.jpg",
    alt: "Установка bi-led линз",
  },
  {
    title: "Улучшение и восстановление оптики",
    description: "Полировка, восстановление прозрачности и защита фар для уверенного света ночью.",
    tag: "Optic",
    image: "../assets/images/services/optika.jpg",
    alt: "Улучшение и восстановление оптики",
  },
  {
    title: "Оклейка цветной антигравийной пленкой",
    description: "Защитная пленка с выразительным цветом: меняет характер авто и закрывает зоны риска.",
    tag: "PPF",
    image: "../assets/images/services/antigravijnaya-plenka.jpg",
    alt: "Оклейка цветной антигравийной пленкой",
  },
  {
    title: "Химчистка",
    description: "Глубокая чистка салона, материалов и трудных зон с бережной детализацией.",
    tag: "Clean",
    image: "../assets/images/services/himchistka.jpg",
    alt: "Химчистка салона",
  },
  {
    title: "Полировка",
    description: "Возвращаем глубину цвета, убираем мелкие дефекты ЛКП и готовим кузов к защите.",
    tag: "Gloss",
    image: "../assets/images/services/polirovka.jpg",
    alt: "Полировка кузова",
  },
  {
    title: "Нанокерамика",
    description: "Премиальная защита кузова с глянцем, гидрофобным эффектом и легким уходом.",
    tag: "Ceramic",
    image: "../assets/images/services/nanokeramika.jpg",
    alt: "Нанокерамика",
  },
  {
    title: "Шумоизоляция",
    description: "Снижаем дорожный шум, делаем салон тише и улучшаем акустический комфорт.",
    tag: "Silence",
    image: "../assets/images/services/shumoizolyaciya.jpg",
    alt: "Шумоизоляция автомобиля",
  },
  {
    title: "Покупка и установка сигнализаций",
    description: "Подбор охранных систем, грамотная установка и настройка под сценарии владельца.",
    tag: "Security",
    image: "../assets/images/services/signalizaciya.jpg",
    alt: "Покупка и установка сигнализаций",
  },
  {
    title: "Установка контурной подсветки",
    description: "Деликатная интерьерная подсветка, которая подчеркивает линии салона без визуального шума.",
    tag: "Ambient",
    image: "../assets/images/services/konturnaya-podsvetka.jpg",
    alt: "Установка контурной подсветки",
  },
  {
    title: "Установка доп. оборудования",
    description: "Камеры, регистраторы, парктроники, ассистенты и другие полезные автомобильные системы.",
    tag: "Upgrade",
    image: "../assets/images/services/dop-oborudovanie.jpg",
    alt: "Установка дополнительного оборудования",
  },
  {
    title: "Запчасти для иномарок",
    description: "Поможем подобрать и заказать детали для обслуживания, ремонта и дооснащения иномарок.",
    tag: "Parts",
    image: "../assets/images/services/zapchasti.jpg",
    alt: "Запчасти для иномарок",
  },
  {
    title: "Авточехлы",
    description: "Подбор и установка чехлов, которые защищают салон и сохраняют аккуратный внешний вид.",
    tag: "Interior",
    image: "../assets/images/services/avtochehly.jpg",
    alt: "Авточехлы",
  },
  {
    title: "Бронепленка / защитная пленка",
    description: "Прозрачная защита кузова, оптики и зон риска от сколов, реагентов и ежедневной нагрузки.",
    tag: "Armor",
    image: "../assets/images/services/bronplenka.jpg",
    alt: "Бронепленка защитная пленка",
  },
  {
    title: "Автосервис",
    description: "Комплексные работы по обслуживанию автомобиля, установке и проверке оборудования.",
    tag: "Service",
    image: "../assets/images/services/avtoservis.jpg",
    alt: "Автосервис",
  },
];

window.servicesData = servicesData;
